fix for compile error: 'mbedtls_md5_starts_ret' was not declared in this scope
this is just a hack to allow compiling. Still need to verify that the functions without "_ret" actually behave the same way.